### ISSUE TITLE
赛季更新啦

### ISSUE THREAD

**Issue by LivingwWell** [Jack0Chan/TFT_Spider#1]
url = 'https://lol.qq.com/zmtftzone/public-lib/versionconfig.json' 这个链接已无法访问

**Comment by Jack0Chan** [comment]
感谢提醒，新版本数据和代码已经更新好。

**Comment by jiabao886** [comment]
作者能更新下这赛季的吗，自己琢磨没搞明白~ ~

**Comment by Jack0Chan** [comment]
> 作者能更新下这赛季的吗，自己琢磨没搞明白~ ~

已更新，请不要在closed issue里提问。
